spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1/admin
    username: postgres
    password: 332584185
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  elasticsearch:
    uris: http://127.0.0.1:8787/es-relay
  jpa:
    properties:
      jakarta:
        persistence:
          jdbc:
            url: jdbc:postgresql://127.0.0.1/admin
            username: postgres
            password: 332584185
            driver: org.postgresql.Driver
nacos:
  server-addr: localhost:8848
rocketmq:
  endpoints: 127.0.0.1:18080
management:
  otlp:
    tracing:
      endpoint: http://47.239.212.78:4318/v1/traces
