server:
  port: 8061 # 服务器端口配置
spring:
  ai:
    dashscope:
      api-key: sk-268354693ec84f74b32a6c237df49cbd
    mcp:
      server:
        name: xiyan-server    # MCP服务器名称
        version: 0.0.1           # 服务器版本号
    vectorstore:
      analytic:
        enabled: false
        collectName: chatBi
        regionId: cn-hangzhou
        dbInstanceId:
        managerAccount:
        managerAccountPassword:
        namespace:
        namespacePassword:
        defaultTopK: 6
        defaultSimilarityThreshold: 0.75
        accessKeyId:
        accessKeySecret:

      mongodb:
        enabled: true

    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-268354693ec84f74b32a6c237df49cbd
      model: qwen-max

  data:
    redis:
      url: redis://127.0.0.1:11212/0
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 4
          # 连接池中的最小空闲连接 默认0
          min-idle: 0

    mongodb:
      uri: mongodb://127.0.0.1:2701/graph
      ssl-enabled: false

  cache:
    # 缓存类型 redis、none(不使用缓存)
    type: redis
    # 缓存时间(单位：ms)
    redis:
      time-to-live: 3600000
      # 缓存null值，防止缓存穿透
      cache-null-values: true

chatbi:
  dbconfig:
    url: jdbc:postgresql://localhost:5432/health_db
    username: postgres
    password: 332584185
    connectiontype: jdbc
    dialecttype: postgresql
    schema: 中文表


